### ISSUE TITLE
Las fichas y los objetos se ven en blanco

### ISSUE THREAD

**Issue by nikuzo** [parvusdomus/ysystem#30]
Me he descargado hace poco el system y me temo que tanto al crear pnj, como jugadores como objetos. Todo aparece en blanco sin mas que el nombre arriba. 

EDIT: Me descargué la versión anterior y funciona. Debe de haber algun problema con los cambios en la V 1.1.1

![image](https://user-images.githubusercontent.com/20879896/166810133-dd20e1b5-9128-44f9-8ec6-217b4a8a3ab4.png)

**Comment by parvusdomus** [comment]
Pues tienes razón, si debe ser que metí la pata en la 1.1.1. En cuanto tenga un rato lo arreglo.

**Comment by parvusdomus** [comment]
Ya está arreglado, si tienes la 1.1.1 instalada desinstala y vuelve a instalar el sistema. Si tienes la 1.1.0 simplemente actualiza.

Gracias por el aviso
