### ISSUE TITLE
Falta habilidad FUERZA BRUTA en ficha de PNJ

### ISSUE THREAD

**Issue by StarSystemX** [parvusdomus/ysystem#33]
- No sale en la ficha del pnj  la habilidad FUERZA BRUTA que se ha añadido en la version revisada.
- Es como cualquier otra habilidad

![PNJ_FuerzaBruta](https://github.com/parvusdomus/ysystem/assets/125882539/04959f92-4fed-461a-971e-73ae95735ff8)

**Comment by parvusdomus** [comment]
Hecho, sale para la próxima v
