### ISSUE TITLE
Nuevos valores dificultad magia

### ISSUE THREAD

**Issue by StarSystemX** [parvusdomus/ysystem#34]
Los valores de magia son ahora **8,12,16** para la dificultad de hechizo.
Quizás para evitar posibles futuros cambios, no estaría mal dejar poner cualquier número

_Cada vez que se haga uso de la magia o la psiónica, e independientemente de que se realice con éxito o no, el personaje verá reducida su cantidad de puntos de Poder del siguiente modo: 2 puntos para hechizos o poderes de dificultad 8, 4 puntos para los de dificultad 12 y 6 puntos para los de dificultad 16. 
Además, algunos hechizos o poderes pueden comportar un gasto fijo y adicional de puntos de Poder.

![DificultaMagia](https://github.com/parvusdomus/ysystem/assets/125882539/c0f30ddf-e427-4719-9519-2f5fb0805caf)

**Comment by parvusdomus** [comment]
Cambiados los valores de dif y el gasto de poder a los valores de ysystem v2. Los casos de gasto fijo o adicional no se contemplan y tendrán que manejarse a mano.
