### ISSUE TITLE
Valores de gasto de Magia nuevos

### ISSUE THREAD

**Issue by StarSystemX** [parvusdomus/ysystem#35]
El valor ha de ser 2,4,6. 
Esto ya veo más difícil de implementar para que sea configurable. Quizás poner el valor GASTO como nueva propiedad?
![GastoMagia](https://github.com/parvusdomus/ysystem/assets/125882539/5bbb4b43-6fbc-48ef-8665-3477a9bf5576)

> 2 puntos para hechizos o poderes de dificultad 8, 4 puntos para los de dificultad 12 y 6 puntos para los de dificultad 16. Además, algunos hechizos o poderes pueden comportar un gasto fijo y adicional de puntos de Poder.

**Comment by parvusdomus** [comment]
Cambiada la forma de calcular el gasto de pp con las dif nuevas
